<a href="https://colab.research.google.com/github/Sank3t-Pand3y/PyTorch/blob/main/IntroPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+2


4

In [2]:
import torch
import numpy as np


In [3]:
# Lists

In [5]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [6]:
#Numpy Array

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.10708486, 0.91114886, 0.16677249, 0.68280714],
       [0.44545073, 0.53217073, 0.66724235, 0.86604528],
       [0.33971475, 0.74030428, 0.87211467, 0.50804678]])

In [9]:
np1.dtype

dtype('float64')

In [10]:
# Tensors

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.3767, -0.2311, -0.8470, -0.6742],
        [ 0.2986, -1.1406, -0.4539, -0.0680],
        [-0.9784, -1.7101,  1.0870,  1.4152]])

In [12]:
# Create tensor out of numpy arrray

In [13]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1071, 0.9111, 0.1668, 0.6828],
        [0.4455, 0.5322, 0.6672, 0.8660],
        [0.3397, 0.7403, 0.8721, 0.5080]], dtype=torch.float64)