<a href="https://colab.research.google.com/github/Sank3t-Pand3y/PyTorch/blob/main/IntroPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+2


4

In [2]:
import torch
import numpy as np


In [3]:
# Lists

In [4]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
#Numpy Array

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.81394958, 0.95819571, 0.33602573, 0.16482908],
       [0.11324869, 0.23332754, 0.98231051, 0.95044666],
       [0.37107681, 0.6775125 , 0.57816939, 0.36062565]])

In [7]:
np1.dtype

dtype('float64')

In [8]:
# Tensors

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [13]:
# Create tensor out of numpy arrray

In [14]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8139, 0.9582, 0.3360, 0.1648],
        [0.1132, 0.2333, 0.9823, 0.9504],
        [0.3711, 0.6775, 0.5782, 0.3606]], dtype=torch.float64)

In [15]:
# YT 3

In [16]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Now we can Reshape above data with different methods

In [18]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
# We can also reshape if we dont know the number of items and that can be done by using -1

In [20]:
my_torch2 = torch.arange(10)
my_torch2


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
# Now through "View" method as well we can reshape the data

In [24]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
my_torch5[2] = 35
my_torch5

tensor([ 0,  1, 35,  3,  4,  5,  6,  7,  8,  9])

In [29]:
my_torch6

tensor([[ 0,  1, 35,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [30]:
# Sliecs :-
# Slices allow you to grab a section of your tensor

In [31]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
my_torch7[7]

tensor(7)

In [33]:
# Grab a slice

In [34]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [35]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [37]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [38]:
# Tensor Math Operation


In [39]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [40]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [41]:
# Add function
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [42]:
# Substraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [43]:
# sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [44]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [47]:
# Multiplication function
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [48]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [49]:
# Division function
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [50]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [51]:
# Remainder function
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [52]:
# Exponent or Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [54]:
# Reassignemnt long method
tensor_a  = tensor_a + tensor_b
tensor_a

tensor([11, 14, 17, 20])

In [55]:
# Reassignment_
tensor_a.add_(tensor_b)
tensor_a

tensor([16, 20, 24, 28])